In [1]:
# target variable is price_range
# Loading the required library 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"F:\carreer\trainRF.csv") # loading the data for analysing and data preprocessing
pd.set_option('display.max_rows',500)

In [3]:
df.shape # to finding the no of data and columns

(2000, 21)

In [4]:
df.head() # see the data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [5]:
df.isnull().sum() # to find the nulls

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [6]:
df.info() # to check the type of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

# Data Sampling

In [7]:
from sklearn.model_selection import train_test_split # Sampling the data

In [8]:
df_train,df_test=train_test_split(df,test_size=.2)

In [9]:
df_train_x = df_train.iloc[:,0:-1]
df_train_y = df_train.iloc[:,-1]

In [10]:
df_test_x = df_test.iloc[:,0:-1]
df_test_y = df_test.iloc[:,-1]

In [11]:
print(df_train_x.shape)
print(df_train_y.shape)
print(df_test_x.shape)
print(df_test_y.shape)

(1600, 20)
(1600,)
(400, 20)
(400,)


In [12]:
# how to build the algrothem


# we import some fuction from sklearn
#we created an object
#run the fit fuction (it build the model) and while run your fit fuction the in put is x,y(x train ,y train)
#we did the perdiction

#run the confustion matrix

# Model build using Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier
dt_df = DecisionTreeClassifier()

In [14]:
dt_df.fit(df_train_x,df_train_y)

DecisionTreeClassifier()

In [15]:
pred= dt_df.predict(df_test_x)
pred

array([1, 1, 2, 3, 1, 2, 0, 0, 1, 3, 0, 2, 2, 2, 0, 1, 3, 1, 3, 2, 3, 2,
       1, 1, 3, 3, 3, 0, 0, 2, 3, 1, 3, 2, 3, 3, 3, 1, 3, 0, 1, 1, 2, 2,
       0, 3, 1, 0, 2, 0, 2, 1, 0, 3, 3, 1, 1, 1, 1, 2, 3, 1, 3, 2, 3, 3,
       2, 1, 1, 1, 3, 3, 3, 2, 2, 0, 2, 2, 1, 1, 3, 1, 3, 0, 0, 2, 1, 1,
       3, 0, 0, 2, 2, 1, 2, 3, 1, 0, 1, 2, 3, 1, 0, 3, 1, 2, 0, 1, 3, 0,
       0, 2, 3, 2, 1, 2, 0, 3, 2, 2, 3, 1, 0, 2, 3, 0, 0, 2, 1, 1, 3, 3,
       3, 0, 2, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 3, 1, 1, 1, 0, 1,
       1, 0, 3, 3, 3, 0, 3, 1, 0, 3, 2, 1, 2, 2, 0, 3, 0, 2, 2, 2, 0, 3,
       2, 3, 3, 1, 0, 2, 2, 3, 3, 0, 0, 3, 1, 0, 3, 3, 2, 0, 3, 0, 0, 1,
       0, 3, 3, 1, 0, 3, 0, 3, 2, 2, 3, 3, 3, 3, 2, 2, 1, 3, 3, 2, 3, 2,
       2, 1, 2, 3, 1, 0, 0, 3, 3, 1, 3, 0, 0, 1, 1, 2, 3, 0, 3, 0, 1, 1,
       0, 3, 3, 0, 3, 3, 1, 1, 2, 3, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 0, 3,
       1, 1, 1, 1, 1, 2, 1, 3, 2, 2, 2, 1, 2, 0, 1, 3, 3, 0, 1, 3, 3, 2,
       3, 2, 2, 1, 0, 0, 0, 2, 1, 0, 0, 1, 3, 3, 3,

In [16]:
pred.shape

(400,)

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
tab_df = confusion_matrix(df_test_y, pred)
tab_df # the confustion matrix is build

array([[76,  7,  0,  0],
       [10, 84, 12,  0],
       [ 0, 13, 80,  9],
       [ 0,  0, 12, 97]], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy_score(df_test_y,pred)*100

84.25

# buiding the random forest

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rfc_mp = RandomForestClassifier(n_estimators=100,criterion='entropy')

In [23]:
rfc_mp.fit(df_train_x , df_train_y)

RandomForestClassifier(criterion='entropy')

In [24]:
pred_rfc = rfc_mp.predict(df_test_x)

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
tab_rfc = confusion_matrix(df_test_y , pred_rfc)

In [27]:
tab_rfc

array([[81,  2,  0,  0],
       [ 6, 90, 10,  0],
       [ 0, 13, 83,  6],
       [ 0,  0, 12, 97]], dtype=int64)

In [28]:
tab_rfc.diagonal().sum()*100/ tab_rfc.sum()

87.75

In [29]:
feature_importance_df = pd.DataFrame({'Featured' :df_train_x.columns , "Importance" : rfc_mp.feature_importances_})

In [30]:
feature_importance_df.sort_values("Importance" , ascending = False)

Featured  Importance
13            ram    0.519257
0   battery_power    0.075969
11      px_height    0.057902
12       px_width    0.057710
8       mobile_wt    0.034598
6      int_memory    0.031420
16      talk_time    0.027534
2     clock_speed    0.024947
10             pc    0.024397
14           sc_h    0.023737
15           sc_w    0.023402
4              fc    0.022648
7           m_dep    0.021487
9         n_cores    0.020488
1            blue    0.006303
18   touch_screen    0.006060
3        dual_sim    0.005844
19           wifi    0.005822
5          four_g    0.005524
17        three_g    0.004953

### note that dont try to plot the randomforest because it will be created but it will not able to understand properly for humabeing

# Building model using the KNN

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn_mp = KNeighborsClassifier()

In [32]:
knn_mp.fit(df_train_x , df_train_y)

KNeighborsClassifier()

In [34]:
pred_mp = knn_mp.predict(df_test_x)

In [35]:
pred_mp

array([1, 2, 2, 3, 1, 2, 0, 0, 1, 3, 0, 2, 2, 2, 0, 1, 3, 2, 3, 1, 3, 2,
       1, 1, 2, 2, 3, 0, 0, 1, 3, 1, 3, 2, 3, 3, 3, 0, 3, 0, 0, 1, 2, 2,
       0, 3, 1, 0, 3, 0, 2, 1, 1, 3, 2, 2, 1, 1, 1, 2, 3, 1, 3, 2, 3, 3,
       2, 1, 1, 1, 3, 2, 3, 2, 1, 0, 3, 2, 2, 2, 3, 1, 3, 1, 0, 2, 1, 1,
       3, 0, 0, 2, 2, 1, 3, 3, 1, 0, 0, 2, 3, 1, 0, 3, 1, 2, 0, 1, 3, 1,
       1, 2, 3, 2, 1, 2, 0, 3, 2, 0, 2, 1, 0, 2, 3, 0, 0, 3, 1, 2, 2, 3,
       2, 0, 2, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 3, 0, 2, 2, 1, 0, 1, 1, 1,
       1, 0, 3, 3, 3, 0, 3, 1, 0, 3, 2, 1, 2, 2, 0, 3, 0, 2, 2, 2, 0, 3,
       2, 3, 3, 1, 0, 2, 2, 3, 3, 0, 0, 3, 1, 0, 2, 3, 2, 0, 3, 0, 0, 1,
       0, 3, 3, 1, 0, 3, 1, 3, 1, 2, 3, 3, 3, 3, 2, 2, 1, 3, 3, 2, 3, 2,
       2, 1, 2, 3, 1, 0, 0, 3, 3, 1, 3, 0, 0, 1, 1, 2, 3, 0, 3, 0, 1, 1,
       1, 3, 3, 0, 3, 3, 1, 1, 3, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 0, 3,
       1, 0, 1, 2, 1, 3, 1, 3, 2, 2, 2, 1, 1, 0, 1, 3, 3, 0, 1, 3, 3, 2,
       3, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 3, 3, 3,

# Confusion Matrix`

In [36]:
from sklearn.metrics import confusion_matrix
tab_mp = confusion_matrix(df_test_y , pred_mp)

In [37]:
tab_mp

array([[78,  5,  0,  0],
       [ 7, 92,  7,  0],
       [ 0,  5, 92,  5],
       [ 0,  0, 10, 99]], dtype=int64)

In [38]:
tab_mp.diagonal().sum()*100/ tab_mp.sum()

90.25